"""Cross-language conformance tests for objects/objects.py.

Consumes tests/test-vectors/objects-tree.json (generated by
tests/test-vectors/_generators/objects_tree.py).
"""
from __future__ import annotations

import pytest

from octospaces_sdk.objects.objects import (
    add_object,
    breadcrumbs,
    build_tree,
    next_order,
    patch_object,
    subtree_ids,
)

from .conftest import load_vector

V = load_vector("objects-tree.json")
NOW = V["now"]


# ── nextOrder ─────────────────────────────────────────────────────────────────


@pytest.mark.parametrize("case", V["nextOrder"])
def test_next_order(case):
    result = next_order(case["siblings"])
    assert result == case["expected"]


# ── buildTree ─────────────────────────────────────────────────────────────────


def test_build_tree_flat():
    v = V["buildTree_flat"]
    tree = build_tree(v["input"])
    ids = [n["id"] for n in tree]
    assert ids == v["expected_ids_in_order"]
    assert len(tree) == v["expected_lengths"]["root"]


def test_build_tree_nested():
    v = V["buildTree_nested"]
    tree = build_tree(v["input"])
    root_ids = [n["id"] for n in tree]
    assert root_ids == v["expected_root_ids"]
    folder = tree[0]
    child_ids = [c["id"] for c in folder.get("children", [])]
    assert child_ids == v["expected_folder_child_ids"]


def test_build_tree_archived():
    v = V["buildTree_archived"]
    tree = build_tree(v["input"])
    root_ids = [n["id"] for n in tree]
    assert root_ids == v["expected_root_ids"]


def test_build_tree_orphan_repaired():
    v = V["buildTree_orphan"]
    tree = build_tree(v["input"])
    root_ids = [n["id"] for n in tree]
    assert root_ids == v["expected_root_ids"]


# ── breadcrumbs ───────────────────────────────────────────────────────────────


@pytest.mark.parametrize("case", V["breadcrumbs"]["cases"])
def test_breadcrumbs(case):
    nodes = V["breadcrumbs"]["input"]
    crumbs = breadcrumbs(nodes, case["nodeId"])
    ids = [n["id"] for n in crumbs]
    assert ids == case["expected_ids"]


# ── subtreeIds ────────────────────────────────────────────────────────────────


@pytest.mark.parametrize("case", V["subtreeIds"]["cases"])
def test_subtree_ids(case):
    nodes = V["subtreeIds"]["input"]
    result = subtree_ids(nodes, case["nodeId"])
    assert sorted(result) == sorted(case["expected_ids"])


# ── addObject ─────────────────────────────────────────────────────────────────


def test_add_object():
    v = V["addObject"]
    result = add_object(v["input_nodes"], v["input"], NOW)
    node = result["node"]
    assert node["title"] == v["expected_title"]
    assert node["parentId"] == v["expected_parentId"]
    assert node["type"] == v["expected_type"]
    assert "id" in node  # id is random but must exist


# ── patchObject ───────────────────────────────────────────────────────────────


def test_patch_object():
    v = V["patchObject"]
    nodes = patch_object(v["input"], v["nodeId"], v["patch"], NOW)
    patched = next(n for n in nodes if n["id"] == v["nodeId"])
    assert patched["title"] == v["expected_title"]
